/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_renemrhfr_lambo4j_LanguageModel */

#ifndef _Included_com_renemrhfr_lambo4j_LanguageModel
#define _Included_com_renemrhfr_lambo4j_LanguageModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_renemrhfr_lambo4j_LanguageModel
 * Method:    initialize
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_renemrhfr_lambo4j_LanguageModel_initialize
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_renemrhfr_lambo4j_LanguageModel
 * Method:    generateResponseNative
 * Signature: (JLjava/util/List;Lcom/renemrhfr/lambo4j/TokenCallback;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_renemrhfr_lambo4j_LanguageModel_generateResponseNative
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_renemrhfr_lambo4j_LanguageModel
 * Method:    cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_renemrhfr_lambo4j_LanguageModel_cleanup
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
